name: PR Preview Environment

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  deploy-preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy to S3 Preview
      run: |
        PREVIEW_PATH="pr-${{ github.event.number }}"
        aws s3 sync dist/ s3://themattyee.com-website/previews/${PREVIEW_PATH}/ --delete
        
    - name: Create CloudFront Invalidation
      run: |
        PREVIEW_PATH="pr-${{ github.event.number }}"
        aws cloudfront create-invalidation \
          --distribution-id E2RLBM05PWXQTH \
          --paths "/previews/${PREVIEW_PATH}/*"
        
    - name: Comment PR
      uses: actions/github-script@v7
      with:
        script: |
          const previewUrl = `https://themattyee.com/previews/pr-${{ github.event.number }}/`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚀 **Preview Environment Deployed**\n\n📱 Preview URL: ${previewUrl}\n\n*Preview will be automatically cleaned up when PR is closed*`
          });

  cleanup-preview:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Cleanup S3 Preview
      run: |
        PREVIEW_PATH="pr-${{ github.event.number }}"
        aws s3 rm s3://themattyee.com-website/previews/${PREVIEW_PATH}/ --recursive
        
    - name: Create CloudFront Invalidation
      run: |
        PREVIEW_PATH="pr-${{ github.event.number }}"
        aws cloudfront create-invalidation \
          --distribution-id E2RLBM05PWXQTH \
          --paths "/previews/${PREVIEW_PATH}/*"
        
    - name: Comment PR
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🧹 **Preview Environment Cleaned Up**\n\nPreview environment has been automatically removed.`
          });