name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

env:
  AWS_REGION: us-east-1

jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build
      env:
        VITE_API_URL: https://zsali94nf5.execute-api.us-east-1.amazonaws.com/prod
        VITE_DEV_MODE: false

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Create PR preview bucket
      run: |
        BUCKET_NAME="themattyee-pr-${{ github.event.number }}"
        echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
        
        # Create S3 bucket for PR preview
        aws s3 mb s3://$BUCKET_NAME --region ${{ env.AWS_REGION }} || true
        
        # Configure bucket for static website hosting
        aws s3 website s3://$BUCKET_NAME \
          --index-document index.html \
          --error-document index.html

    - name: Deploy PR preview
      run: |
        aws s3 sync dist/ s3://$BUCKET_NAME --delete
        echo "🌐 PR Preview URL: http://$BUCKET_NAME.s3-website-${{ env.AWS_REGION }}.amazonaws.com"

    - name: Comment PR with preview link
      uses: actions/github-script@v7
      with:
        script: |
          const bucketName = process.env.BUCKET_NAME;
          const previewUrl = `http://${bucketName}.s3-website-${{ env.AWS_REGION }}.amazonaws.com`;
          
          const comment = `## 🚀 PR Preview Deployed
          
          Your changes have been deployed to a preview environment:
          
          🌐 **Preview URL:** ${previewUrl}
          
          This preview will be updated automatically when you push new changes to this PR.
          
          > ⚠️ Note: Preview uses HTTP (not HTTPS) so browser may show "not secure" - this is normal for previews.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

  cleanup:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Cleanup PR preview
      run: |
        BUCKET_NAME="themattyee-pr-${{ github.event.number }}"
        aws s3 rb s3://$BUCKET_NAME --force || true
        echo "🗑️ Cleaned up PR preview bucket: $BUCKET_NAME"

    - name: Comment PR cleanup
      uses: actions/github-script@v7
      with:
        script: |
          const comment = `## 🧹 PR Preview Cleaned Up
          
          The preview environment for this PR has been automatically cleaned up.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });